security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        # api user detais
        # admin/admin123
    providers:
        in_memory_users:
            memory:
                users:
                    admin:
                        password: '$2y$13$srhDwQ/lFMQ2pldT/EgR0e5zI/5xNmunicuXqGO6.WDqmOGeOXBG2'
                        roles: ROLE_ADMIN
        app_user_provider:
            entity:
                class: App\Entity\Usermanagement\User
                property: email
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern:  ^/api
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                provider: app_user_provider
                success_handler: App\Security\Authentication\LoginSuccessHandler
                failure_handler: App\Security\Authentication\LoginFailureHandler

            logout:
                path: /api/logout
                
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
